# Generated by Django 5.2.6 on 2025-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(help_text='Enter ingredients separated by commas', max_length=200)),
                ('instructions', models.CharField(max_length=250)),
                ('cooking_time', models.IntegerField(help_text='Cooking time in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('cover_image', models.ImageField(blank=True, default='recipes/covers/default.jpg', null=True, upload_to='media/cover_images/')),
            ],
        ),
    ]
