# Generated by Django 5.2.6 on 2025-09-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(blank=True, default='recipes/cover_images/default.jpg', null=True, upload_to='media/cover_images/'),
        ),
    ]
