# Generated by Django 5.2.6 on 2025-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_cover_image_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover_images/default.jpg', null=True, upload_to='cover_images/'),
        ),
    ]
